name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version to bump to
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn bump --version ${{ github.event.inputs.version }}
      - run: |
          git config --local user.email "pvinis+bot@gmail.com"
          git config --local user.name "Github Actions Bot"
          git commit -m "Bump to ${{ github.event.inputs.version }}"
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
